"""empty message

Revision ID: 0c730cd7452e
Revises: 26e93d520b12
Create Date: 2024-04-27 20:50:38.565244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c730cd7452e'
down_revision: Union[str, None] = '26e93d520b12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'info',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=1000),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'info',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
