"""empty message

Revision ID: 169bbacce4ed
Revises: 62bbb70ffc52
Create Date: 2024-04-30 23:51:23.643908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '169bbacce4ed'
down_revision: Union[str, None] = '62bbb70ffc52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('user', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'message', 'users', ['user'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'user')
    # ### end Alembic commands ###
