"""empty message

Revision ID: 1b11aedfe72e
Revises: f3828c3f889b
Create Date: 2024-04-29 22:55:15.355502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b11aedfe72e'
down_revision: Union[str, None] = 'f3828c3f889b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('user', sa.Integer(), nullable=False))
    op.add_column('message', sa.Column('user_', sa.Integer(), nullable=False))
    op.drop_constraint('message_user_id_fkey', 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'users', ['user'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'message', 'users', ['user_'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('message', 'chat_id')
    op.drop_column('message', 'user_id')
    op.drop_column('message', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('message', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('message', sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key('message_user_id_fkey', 'message', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('message', 'user_')
    op.drop_column('message', 'user')
    # ### end Alembic commands ###
