"""empty message

Revision ID: a5a14a2a2c00
Revises: b6b93ade271b
Create Date: 2024-04-30 11:14:45.068718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5a14a2a2c00'
down_revision: Union[str, None] = 'b6b93ade271b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('message_user_user__key', 'message', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('message_user_user__key', 'message', ['user', 'user_'])
    # ### end Alembic commands ###
