"""empty message

Revision ID: c9409c4a54aa
Revises: 
Create Date: 2024-04-30 11:04:41.100247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9409c4a54aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_chat_id_key', 'chat', type_='unique')
    op.drop_column('chat', 'chat_id')
    op.create_foreign_key(None, 'message', 'chat', ['chat_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.add_column('chat', sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('chat_chat_id_key', 'chat', ['chat_id'])
    # ### end Alembic commands ###
