"""empty message

Revision ID: da1d7ae3d4f4
Revises: a5a14a2a2c00
Create Date: 2024-04-30 11:16:14.804311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da1d7ae3d4f4'
down_revision: Union[str, None] = 'a5a14a2a2c00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('user', sa.Integer(), nullable=False))
    op.add_column('chat', sa.Column('user_', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'chat', 'users', ['user_'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'chat', 'users', ['user'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('message_user__fkey', 'message', type_='foreignkey')
    op.drop_constraint('message_user_fkey', 'message', type_='foreignkey')
    op.drop_column('message', 'user')
    op.drop_column('message', 'user_')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('user_', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('message', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('message_user_fkey', 'message', 'users', ['user'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('message_user__fkey', 'message', 'users', ['user_'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'chat', type_='foreignkey')
    op.drop_constraint(None, 'chat', type_='foreignkey')
    op.drop_column('chat', 'user_')
    op.drop_column('chat', 'user')
    # ### end Alembic commands ###
